### ISSUE TITLE
Sweet IPFS from Google play crashes on startup

### ISSUE THREAD

**Issue by FruityWelsh** [hazae41/sweet-ipfs#10]
Application starts but crashed when rocket is clicked. Giving 2 "Unfortunately sweet ipfs has crashed" messages.

> using the build from Google play
> Android version 6.0.1
> Init settings are blank
> Start settings are: --enable-pubsub-experiment --enable-namesys-pubsub

**Comment by FruityWelsh** [comment]
Shot in the dark troubleshooting(unsuccessful):
Reinstalled
Removed start arg "--enable-namesys-pubsub"
Tried removing start arg "--enable-pubsub-experiment"

**Comment by Hazae41** [comment]
Do you have more informations about the error?

**Comment by FruityWelsh** [comment]
Sure! Here is the crash report
[TraceDroid Report] fr.rhaz.ipfs.sweet
file: /data/user/0/fr.rhaz.ipfs.sweet/files/0.2.4-1549548953571.tracedroid
Android Version: 6.0.1
Phone Model: S60
TraceDroid Version: 1.1
TraceDroid extra: 
Stacktrace: 
 android.app.RemoteServiceException: Bad notification posted from package fr.rhaz.ipfs.sweet: Couldn't create icon: StatusBarIcon(icon=Icon(typ=RESOURCE pkg=fr.rhaz.ipfs.sweet id=0x7f070074) visible user=0 )
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1507)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Log: 
 0 D: Writing unhandled exception to: /data/user/0/fr.rhaz.ipfs.sweet/files/0.2.4-1549548953571.tracedroid
1 D: current handler class=com.android.internal.os.RuntimeInit$UncaughtHandler
file: /data/user/0/fr.rhaz.ipfs.sweet/files/0.2.4-1549548957385.tracedroid
Android Version: 6.0.1
Phone Model: S60
TraceDroid Version: 1.1
TraceDroid extra: 
Stacktrace: 
 android.app.RemoteServiceException: Bad notification posted from package fr.rhaz.ipfs.sweet: Couldn't create icon: StatusBarIcon(icon=Icon(typ=RESOURCE pkg=fr.rhaz.ipfs.sweet id=0x7f070074) visible user=0 )
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1507)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Log: 
 0 D: Writing unhandled exception to: /data/user/0/fr.rhaz.ipfs.sweet/files/0.2.4-1549548957385.tracedroid
1 D: current handler class=com.android.internal.os.RuntimeInit$UncaughtHandler
